### ISSUE TITLE
When will there be a release version? 

### ISSUE THREAD

**Issue by chenjianjx** [evernote/evernote-sdk-python3#15]
We only need it to be robust.  It doesn't have to contain every feature of the APIs. 

We want to be able to integrate it with pip.

**Comment by dvska** [comment]
Hi Devs!
Is this the same package -> https://pypi.python.org/pypi/evernote3 ?
Thanks

**Comment by akhaku** [comment]
Appears to be, but also it's unofficial - the individual who published it isn't affiliated with Evernote.

**Comment by pydolan** [comment]
@akhaku / devs -- can you release an official pypi package or take over management of the existing pypi package (https://pypi.python.org/pypi/evernote3)?  

It seems like a somewhat major security and PR risk to have some unknown Pypi user representing Evernote. The author of this package is even listed as "Evernote Corporation".

Thanks!

**Comment by akhaku** [comment]
Thanks for the nudge - I've reached out to the developer via email and twitter, will give them a few days before we going down other avenues.

**Comment by akhaku** [comment]
@ahxxm came through really quick, thank you so much! Thanks for all your work on publishing it and maintaining it thus far <3.

**Comment by ahxxm** [comment]
I've been maintaining and using evernote3 pypi package myself for a while, feels good to transfer ownership to Evernote.  <3
