### ISSUE TITLE
Will the Python 3 SDK be released before Python 2.7 EOL?

### ISSUE THREAD

**Issue by saifelse** [Evernote/evernote-sdk-python3#25]
Hi,

The Python 2.7 EOL is quickly approaching, and I noticed that there hasn't been any work on this repo in the last 2 years. So I just wanted to confirm what I fear that this SDK won't be released before the end of the year?

It's unfortunate as I'm working on an application that has an in integration with Evernote that we'll have to sunset as a result.

Thanks in advance for any timeline updates you can share!

**Comment by sanketplus** [comment]
Since the python2 has EOL'ed, are there any plans to make this SDK default and start supporting it officially?

**Comment by ttimasdf** [comment]
> This would be great. Not sure what happened these last few days but I can no longer share notebooks using this SDK. Looks like the email is being passed as username when sharing notebooks. No idea why, I am not aware of any new changes to the API.

Here's an assumption. Evernote PM is thinking that API and interoperability makes no profit. Only reduce the cost of users migrating to other note products.

**Comment by vitaly-zdanevich** [comment]
Wow, not planned, but why?
