### ISSUE TITLE
Proxy Support

### ISSUE THREAD

**Issue by bordaigorl** [evernote/evernote-sdk-python3#6]
Hi, I've noticed that the sdk for python2 includes a version of THttpClient that supports proxies while this one does not explicitly offer this.
Is there a workaround? Are you planning to update this?

**Comment by matthewayne** [comment]
Evernote uses Apache Thrift to communicate with its clients as well as 3rd party applications.  The code you see here is generate by the Thrift complier and helper methods and classes are added on top to aid in development of 3rd party application.  The Thrift methods, objects and classes (including THttpClient) come from the Apache Thrift project and not Evernote.

Evernote does not have any plans to add proxy support to THttpClient (but we will update the Thrift generated code)

The Thrift source code can be found on Github here: https://github.com/apache/thrift/

**Comment by daisuke-yoshimoto** [comment]
Any update ?

**Comment by ogsy** [comment]
Thrift seems to have been fixed as of 0.10.0 (https://issues.apache.org/jira/browse/THRIFT-3798) - any chance of getting this updated?

**Comment by bordaigorl** [comment]
@ogsy Unfortunately it is not sufficient to replace the Thrift library with the new one, the Evernote SDK must be compiled with the new version as well and only the Evernote team can do that 😞
